### ISSUE TITLE
npm start fails due to Redis

### ISSUE THREAD

**Issue by niklr** [iotexproject/babel-api#9]
Could not find any information in the README about Redis configuration.

```
npm start

> xxx_server@1.0.0 start /home/ubuntu/Projects/iotex/babel-api
> node dist/api.js

events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/home/ubuntu/Projects/iotex/babel-api/node_modules/redis/index.js:342:14)
    at Socket.<anonymous> (/home/ubuntu/Projects/iotex/babel-api/node_modules/redis/index.js:223:14)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxx_server@1.0.0 start: `node dist/api.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xxx_server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-05-28T12_37_35_704Z-debug.log
```

**Comment by maswalker** [comment]
Sorry for late response.
I added the guide to configure redis in README.
